name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Check if it should deploy to production
        id: deploy
        if: github.ref == 'refs/heads/master'
        run: echo "::set-output name=args::--prod"

      - name: Deploy to Now
        uses: amondnet/now-deployment@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          zeit-token: ${{ secrets.NOW_TOKEN }}
          zeit-team-id: team_3y8CtWxEFFZzrkw9VHAK6Rsn
          now-args: ${{ steps.deploy.outputs.args }}
